version: '2'

services:
  # web:
  #   build:
  #     context: store-app
  #     dockerfile: Dockerfile 
  #   volumes:
  #     - "./store-app:/src/app"
  #   depends_on:
  #     - service
  #     - store-keycloak
  #   ports:
  #     - "4200:4200"

  # service:
  #   build:
  #     context: store-service
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - store-keycloak
  #     - postgres-database
  #   volumes:
  #     - "./store-service:/src/service"
  #   ports: 
  #     - "3000:3000"

  store-keycloak:
    build: 
      context: Keycloak
      dockerfile: Dockerfile
    depends_on:
      - postgres-database
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin1
      - KEYCLOAK_LOGLEVEL=TRACE
      - POSTGRES_PORT_5432_TCP_ADDR=postgres-database
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - "8080:8080"
      - "9990:9990"
      - "443:8443"

  postgres-database:
    image: postgres:9.5
    restart: always
    environment:
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports: 
      - "5432:5432"
    volumes:
      - ./database/init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

networks:
  default:
    ipam:
      config:
      - subnet: 172.100.10.0/24
        gateway: 172.100.10.1

